---
- name: Uninstall old versions of Docker
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: Install necessary packages for managing DNF repositories
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
    update_cache: true

- name: Add Docker repository
  ansible.builtin.shell:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  register: add_repo_result

- name: Debug repo addition result
  ansible.builtin.debug:
    var: add_repo_result

- name: Install Docker Engine
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Verify Docker installation
  ansible.builtin.shell:
    cmd: docker run hello-world
  register: verify_docker_result

- name: Debug Docker verification result
  ansible.builtin.debug:
    var: verify_docker_result
