---
# Load Debian specific tasks
- name: (Debian) import tasks
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

# Load Redhat specific tasks
- name: (Redhat) import tasks
  import_tasks: redhat.yml
  when: ansible_facts['os_family'] in ['RedHat', 'Rocky']

# Common tasks
- name: Add "main_user" in "docker" group
  ansible.builtin.user:
    name: "{{ main_user }}"
    groups: docker
    append: true
    state: present
