---
- name: Debian family tasks
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Redhat family tasks
  import_tasks: redhat.yml
  when: ansible_os_family in ['Redhat', 'Rocky']
