---
- name: (REDHAT) Include variables
  ansible.builtin.include_vars:
    file: redhat.yml

- name: (REDHAT) Install Apache
  ansible.builtin.dnf:
    name:
      - httpd
      - mod_ssl
    state: present
    update_cache: true

- name: Restart and Enable 'apache2.service'
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true