---
- name: (DEBIAN) Include variables file
  ansible.builtin.include_vars:
    file: vars/debian.yml

- name: (DEBIAN) Install NFS
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - portmap
    state: present
  notify: Restart-Enable NFS
