---
- name: (REDHAT) Install required packages
  ansible.builtin.dnf:
    name:
      - curl
      - git
      - wget
    update_cache: true
    state: present

- name: (REDHAT) Install Gitlab-Runner repo
  ansible.builtin.shell:
    cmd: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash

- name: (REDHAT) Install Gitlab-Runner
  ansible.builtin.dnf:
    name: 
      - gitlab-runner
    update_cache: true
    state: present

- name: (REDHAT) Start-Enable gitlab-runner.service
  ansible.builtin.service:
    name: gitlab-runner
    state: started
    enabled: true
